version: "3.8"

services:
  server:
    build: ./server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ADMIN_CODE=${ADMIN_CODE}
    depends_on:
      - db
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build:
      context: ./client
      args:
        - VITE_INN=${INN}
    ports:
      - "${CLIENT_PORT}:80"
      - "${CLIENT_SSL_PORT}:443"
    volumes:
      - ./client/ssl:/etc/letsencrypt
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
